name = "SphericalHarmonics"
uuid = "c489a379-e885-57ff-9236-bd896d33c250"
version = "0.1.19"

[deps]
IrrationalConstants = "92d709cd-6900-40b7-9082-c6be49f344b6"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
SphericalHarmonicArrays = "9dd28c12-4719-4e7d-b634-e7b733a6d046"
SphericalHarmonicModes = "0e9554e2-b38b-11e9-16d7-9d9abfec665a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ForwardDiff = "0.10"
HCubature = "1"
IrrationalConstants = "0.1"
LegendrePolynomials = "0.3"
MultiplesOfPi = "0.5"
OffsetArrays = "1"
Setfield = "0.7, 0.8"
SpecialFunctions = "0.8, 1, 2"
SphericalHarmonicArrays = "0.4.4"
SphericalHarmonicModes = "0.4.7"
StaticArrays = "1"
WignerD = "0.1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
LegendrePolynomials = "3db4a2ba-fc88-11e8-3e01-49c72059a882"
MultiplesOfPi = "b749d01f-fee9-4313-9f11-89ddf7ea9d58"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WignerD = "87c4ff3e-34df-11e9-37a7-516cea4e0402"

[targets]
test = ["Aqua", "ForwardDiff", "HCubature", "LegendrePolynomials", "MultiplesOfPi", "OffsetArrays", "Test", "WignerD"]
